name: Travis Yip
markdown: kramdown

collections:
# # Work in Progress permalink
  wips:
    output: true
  # post folder
  posts:
    output: true
    permalink: /portfolio/:title/
  # blog
  blogs:
    output: true
    permalink: /blog/:title

# Google Analytics xl nzlk
google_analytics: G-0BEDED78PR

# RSS feed
plugins:
  - jekyll-feed
  - jekyll-paginate

# paginate version 1
paginate: 2
paginate_path: /portfolio/page:num/

permalink: pretty

