name: Travis Yip
markdown: kramdown

# blog post link
permalink: /blog/:year/:month/:day/:title

# previous work in portfolio page
permalink: /portfolio/:path

# collections:
#   portfolio:
#     output: true

# # Work in Progress permalink
permalink: /wips/:path
# collections:
#   wips:
#     output: true

# Google Analytics
google_analytics: G-0BEDED78PR