name: Travis Yip
markdown: kramdown

# blog post link
permalink: /blog/:year/:month/:day/:title


collections:
# # Work in Progress permalink
  wips:
    output: true
# portfolio folder
  portfolio:
    output: true
  

# Google Analytics
google_analytics: G-0BEDED78PR