name: Travis Yip
markdown: kramdown

# blog post link
permalink: /blog/:year/:month/:day/:title

# previous work in portfolio page
collections:
  portfolio:
    output: true

# Work in Progress permalink
permalink: /wips/:title

# Google Analytics
google_analytics: G-0BEDED78PR