name: Travis Yip
markdown: kramdown

collections:
# # Work in Progress permalink
  wips:
    output: true
  # post folder
  posts:
    output: true
    permalink: /post/:title/
  # blog
  blogs:
    output: true
    permalink: /blog/:title

# Google Analytics xl nzlk
google_analytics: G-0BEDED78PR

# RSS feed
plugins:
  - jekyll-feed
  - jekyll-paginate

# paginate
paginate: 5
paginate_path: /portfolio/page:num
#  enabled: true
#  collection: 'posts'
#  per_page: 2
#  title: 'Travis Yip | Porfolio - page :num'
#  category: 'posts'
#  permalink: 'portfolio/page=:num/'

permalink: pretty

