name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        # Ensure Node.js 20 is used by specifying node-version for this action
        with:
          node-version: '20'

      # Setup Node.js to run the actions on Node 20
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies inc Jekyll Paginate-v2
        run: |
          gem install bundler
          bundle install

      - name: Build the Jekyll site locally
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Build and deploy Jekyll site"
          git push origin gh-pages
